### PR TITLE
Small updates

### PR DESCRIPTION
**Pull request by RondingTagPro**
Hi, I've fixed a bug regarding the stroke width of the large text, modernized the rendering of TagPro and Rolling Bomb on players (in line with the current version of the game), and added a missing flair.

### CODE REVIEW

**Comment by chrahunt** [comment]
Hi! I haven't updated the contribution section of the master branch, so this is my fault. Do you mind targeting your changes for the [dev](https://github.com/chrahunt/TagProReplays/tree/dev) branch?

**Comment by RondingTagPro** [comment]
Just walk through the diff manually, the code changes are small. I'm not familiar with the dev directory structure anyways.

Also, I noticed that [map_draw_functions.js lines 366-367](https://github.com/chrahunt/TagProReplays/blob/master/map_draw_functions.js#L366):

    point.x + 10,
    point.y - 30,

should be:

    point.x + 13,
    point.y - 32,

**Comment by chrahunt** [comment]
Lucky for you the README has the directory structure laid out. In any case, I'll take care of this (and those lines) later. Thanks!

**Comment by ballparts** [comment]
>Also, I noticed that map_draw_functions.js lines 366-367:

>`point.x + 10,   
point.y - 30,`


>should be:

>`point.x + 13,
point.y - 32,`

Are you saying I shouldn't have just eyeballed things? :stuck_out_tongue:

**Comment by chrahunt** [comment]
Satisfied by #98. Thanks @RondingTagPro!

**Pull request closed without merging**
