### PR TITLE
Switch from Whammy to Groover for WebM file creation

### PR DESCRIPTION
**Pull request by SomeBall-1**
Maybe unnecessary. Rendering speed seems to be about the same (have only done very minimal testing)

### CODE REVIEW

**Comment by ballparts** [comment]
Any evidence that it handles webp parsing more correctly than Whammy? The code looks a bit cleaner at least imo, which may lead to easier bug fixes later down the line.

**Comment by SomeBall-1** [comment]
Just from looking at the code I couldn't tell you if it's any more up to spec for webp. Since it's my understanding there aren't any replays that Whammy consistently fails on, I'm not sure how you could test for areas where Groover works and Whammy does not.

Code does look cleaner, but since it's not as popular as Whammy and also lacks a repo page you'll miss out on updates and issues+solutions encountered by others. Groover was grabbed from here for reference: http://stackoverflow.com/documentation/html5-canvas/3689/media-types-and-the-canvas/19522/capture-canvas-and-save-as-webm-video#t=201611241920300650936. Although I already needed to fix a small bug (commit here)[https://github.com/chrahunt/TagProReplays/pull/114/commits/b967c1fbebab82545084ee1d3310d7634d1a7457#diff-2e840fb0d40006c6dbc2df78802f8222].

**Comment by ballparts** [comment]
That's one of my concerns as well. Although we use an older version of Whammy, we still benefit from its (I assume) larger user base for some modicum of bug fixing, etc. It might be worthwhile to contact the author and set up a repo for it. At the very least it will provide an additional search result when people type "javascript canvas to video" into Google besides Whammy and sometimes [RecordRTC](http://recordrtc.org/) (which uses a modified Whammy for its high quality stuff) :)

**Comment by chrahunt** [comment]
It looks like it is making the same assumptions about the contents of the WEBP as Whammy (and so would suffer the same issue assuming there's alpha information). Apart from that I think it would be better to have this in its own repository with its own tests.

**Comment by SomeBall-1** [comment]
Not useful enough to switch.

**Pull request closed without merging**
